[URL]
SpliceuUrl=http://172.29.3.87:7001/api/AutomationApi/SpliceLot
SurUrl=http://172.29.3.87:7001/api/AutomationApi/CrystalAppearanceCheckInsert
JdUrl=http://172.29.3.87:7001/api/AutomationApi/CutComplete
DpUrl=http://172.29.3.87:7001/api/AutomationApi/PoleknifeComplete
GmUrl=http://172.29.3.87:7001/api/AutomationApi/RollGrindingComplete
CrystaInformationUrl=http://172.29.3.87:7001/api/AutomationApi/GetCrystalMessage
CrystalStateUrl=http://172.29.3.87:7001/api/AutomationApi/GetCrystalState
GetLotWayUrl=http://172.29.3.87:7001/api/AutomationApi/GetLotWay
[IPAddress]
PlcIpddress=192.168.0.1
[PLCAddress]
;切方下料报表
QfDownCommand_0 = 4002
QfDownCommand_1 = 4000
QfDownWireCost_0 = 50122
QfDownWireCost_1 = 50122
QfDownWireLeft_0 = 50018
QfDownWireLeft_1 = 50018
QfDownWireBreakTimes_0 = 50002
QfDownWireBreakTimes_1 = 50002
QfDownCode_0 = 50022
QfDownCode_1 = 50032
QfWidth1_0=50048
QfWidth2_0=50052
QfWidth1_1=50050
QfWidth2_1=50054
QfstartHour=50004
Qfstartmin=50006
Qfstartsec=50008
QfendHour=50010
Qfendmin=50012
Qfendsec=50016






